name: 🐞 Bug
description: File a bug/issue
title: "[BUG] <title>"
labels: [Bug]
body:
- type: textarea
  attributes:
    description: Provide a general summary of the issue in the Title above
  validations:
    required: false
- type: textarea
  attributes:
    label: Expected Behavior
    description: If describing a bug, tell us what happens instead of the expected behavior, If suggesting a change/improvement, explain the difference from current behavior
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps to Reproduce (for bugs)
    description: Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. Include code to reproduce, if relevant
    value: |
      1.
      2.
      3.
      ...
  validations:
    required: false
- type: input
  id: runningInfo
  attributes:
    label: Run options
    description: on which target repo?
  validations:
    required: true
- type: textarea
  attributes:
    label: Environment
    description: |
      examples:
        - **OS**: Ubuntu 20.04
        - **Node**: 13.14.0
        - **npm**: 7.6.3
    value: |
        - OS: 
        - Node: 
        - npm: 
    render: markdown
  validations:
    required: false
- type: textarea
  attributes:
    label: Extra info
    description: |
      Any additional information to help explain the impact, solution or requirement      
      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
