const CONSTANTS = {};
CONSTANTS.ENDPOINT = {};

CONSTANTS.PORT = process.env.PORT || "3001";

//CONSTANTS.ENDPOINT.LIST = "/list";

// CONSTANTS.ENDPOINT.MASTERDETAIL = "/masterdetail";

CONSTANTS.ENDPOINT.OWNERS = "/owners";

CONSTANTS.ENDPOINT.APTS = "/apts";

CONSTANTS.ENDPOINT.CONTRACTS = "/contracts";

CONSTANTS.ENDPOINT.RESIDENTS = "/residents";

CONSTANTS.ENDPOINT.REPORTS = "/reports";

CONSTANTS.ENDPOINT.CHEQUES = "/cheques";

CONSTANTS.ENDPOINT.DOCUMENTS = "/documents";

CONSTANTS.ENDPOINT.ADMINS = "/admin";




module.exports = CONSTANTS;
